include: common.yaml

packages:
  # ?
  - rootfiles
  # https://bugzilla.redhat.com/show_bug.cgi?id=1409920
  - tar
  - vim-minimal
  - dnf
  # https://fedorahosted.org/fesco/ticket/1312#comment:29
  - dnf-yum
  - sudo

exclude-packages:
  - glibc-langpack-en
  - langpacks-en

postprocess:
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail

    # Remove some extraneous files
    rm -rf /var/cache/dnf/*
    rm -rf /tmp/*

    # https://pagure.io/atomic-wg/issue/308
    printf "tsflags=nodocs\n" >>/etc/dnf/dnf.conf

    # https://bugzilla.redhat.com/show_bug.cgi?id=1343138
    # Fix /run/lock breakage since it's not tmpfs in docker
    # This unmounts /run (tmpfs) and then recreates the files
    # in the /run directory on the root filesystem of the container
    #
    # We ignore the return code of the systemd-tmpfiles command because
    # at this point we have already removed the /etc/machine-id and all
    # tmpfiles lines with %m in them will fail and cause a bad return
    # code. Example failure:
    #   [/usr/lib/tmpfiles.d/systemd.conf:26] Failed to replace specifiers: /run/log/journal/%m
    #
    # umount /run
    # rm -f /run/nologin # https://pagure.io/atomic-wg/issue/316

    # Final pruning
    rm -rfv /var/cache/* /var/log/* /tmp/*

    # See: https://bugzilla.redhat.com/show_bug.cgi?id=1051816
    # NOTE: run this in nochroot because "find" does not exist in chroot
    KEEPLANG=en_US
    for dir in locale i18n; do
        find /usr/share/${dir} -mindepth  1 -maxdepth 1 -type d -not \( -name "${KEEPLANG}" -o -name POSIX \) -exec rm -rfv {} +
    done
