name: "Build container images"

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.yaml"
      - ".github/workflows/*.yml"
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "*.yaml"
  #     - ".github/workflows/*.yml"
  # Disabled for now as this is only an experiment
  # schedule:
  #   - cron:  '0 0 * * MON'

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  REGISTRY: "quay.io/travier"

jobs:
  build-push-image:
    # strategy:
    #   matrix:
    #     image: ['base', 'base-minimal', 'minimal', 'nginx']

    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:38
      options: "--user root --privileged -v /var/tmp:/var/tmp -v /tmp:/tmp"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup just
        run: |
          dnf install -y just

      - name: Build image
        run: just github
        # run: just github ${{ matrix.image }}
