name: "Build nginx container image"

env:
  IMAGE_NAME: "nginx"
  REGISTRY: "quay.io/travier"

on:
  pull_request:
    branches:
      - main
    paths:
      - manifest.yaml
      - .github/workflows/nginx.yml
  push:
    branches:
      - main
    paths:
      - manifest.yaml
      - .github/workflows/nginx.yml
  schedule:
    - cron:  '0 0 * * MON'

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:38
      options: "--user root --privileged -v /var/tmp:/var/tmp -v /tmp:/tmp"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          dnf install -y rpm-ostree just
          dnf install -y 'dnf-command(debuginfo-install)'
          dnf debuginfo-install -y rpm-ostree ostree

      - name: Build image
        run: just
